In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install "pymongo[srv]"

     |████████████████████████████████| 269 kB 4.3 MB/s 


In [ ]:
import pymongo
import pandas as pd
import numpy as np
from bson.objectid import ObjectId
from tqdm import tqdm
import pprint
from sklearn.neighbors import NearestNeighbors
import pickle

In [ ]:
myclient = pymongo.MongoClient("mongodb+srv://modscholar_dev_lucas:Aw1rDosixzshk1I3@cluster1.0xpfm.mongodb.net/dev?retryWrites=true&w=majority")
mydb = myclient["dev"]
mycol = mydb["papers"]

In [ ]:
documents_with_tokens_split = pd.read_pickle("./drive/MyDrive/Colab Notebooks/CE/data/hasDOI/documents_with_tokens_split.pickle")
len(documents_with_tokens_split)

1026139

In [ ]:
documents_with_tokens_split = pd.read_pickle("./drive/MyDrive/Colab Notebooks/CE/data/hasDOI/documents_with_tokens_split_hep_th.pickle")

In [ ]:
print("Number of Documents: " + str(len(documents_with_tokens_split)))
display(documents_with_tokens_split.head(1))

print("\nNumber of Embeddings: " + str(len(embeddings)))
embeddings

Number of Documents: 115458


level_0  index         id            authors  \
0        0      5  0704.0015  [Stahn Christian]   

                                               title  \
0  Fermionic superstring loop amplitudes in the p...   

                             doi  category  \
0  10.1088/1126-6708/2007/05/034  [hep-th]   

                                            abstract  \
0    The pure spinor formulation of the ten-dimen...   

                                      processed_text  \
0  pure spinor formulation ten-dimensional supers...   

                                        tokens_split  
0  [pure, spinor, formulation, ten-dimensional, s...


Number of Embeddings: 115458


array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.21877966, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])



```
# This is formatted as code
```

### Uploading to Mongo

In [ ]:
n = len(documents_with_tokens_split)

for idx, document in enumerate(tqdm(documents_with_tokens_split.iterrows(), total=n)):  

    newPaper = { 
        "idx": idx, 
        "title": document[1][4],
        "arxiv_id": document[1][2],
        "authors": document[1][3]
      }
    
    if idx >n:
      break

    mycol.insert_one(newPaper)

100%|██████████| 115458/115458 [2:49:55<00:00, 11.32it/s]


### Deleteing Documents

Use `.delete_many({})` to delete everything from a collection in a database.

In [ ]:
myquery = {}
x = mycol.delete_many(myquery)

### Querying Mongo

In [ ]:
search="Fermionic"

skip = 0
limit = 10
match = { "$text": { "$search": search } }

pipeline = [
  {
    "$search": {
      "index": 'searchPapers',
      "text": {
        "query": 'Fermionic',
        "path": {
          'wildcard': '*'
        }
      }
    }
  },
  {
    "$facet": {
      "groups": [
        { "$skip": skip * limit },
        { "$limit": limit }
      ],
      "count": [
        { "$count": 'count' }
      ]
    }
  }
]


''' pipeline = [
    { "$match": match },
    {
      "$facet": {
        "groups": [
          { "$skip": skip * limit },
          { "$limit": limit }
        ],
        "count": [
          { "$count": 'count' }
        ]
      }
    }
  ] '''

#pprint.pprint(list(mycol.aggregate(pipeline)))
result = mycol.aggregate(pipeline)
list(result)

### save nearest neighbor

In [ ]:
#tfidf_embeddings = np.load("./drive/MyDrive/Colab Notebooks/CE/data/embeddings/tfidf_embeddings.npy")
embeddings = np.load("/content/drive/MyDrive/Colab Notebooks/CE/data/hasDOI/embeddings_hep_th/tfidf_embeddings.npy")

In [ ]:
n_neighbor=10 
printOutput=True

number_of_rows = embeddings.shape[0]
test_indeces = np.random.choice(number_of_rows, size=10, replace=False)
sample_embeddings = embeddings[test_indeces, :]

nearNeighbor = NearestNeighbors(n_neighbors=n_neighbor,
                         metric='cosine',
                         algorithm='brute',
                         n_jobs=-1)

nearNeighbor.fit(embeddings)


_, near_idx = nearNeighbor.kneighbors(X=sample_embeddings, n_neighbors=n_neighbor, return_distance=True)

if printOutput:
  print("\n======================== Nearest Neighbor ========================")
  print("\nInput shape: " + str(embeddings.shape))
  print("\nOutput shape: " + str(near_idx.shape))
  print("\nOutput type: " + str(type(near_idx)))
  print("\nOutput: " + str(near_idx))


======================== Nearest Neighbor ========================

Input shape: (115458, 512)

Output shape: (10, 10)

Output type: <class 'numpy.ndarray'>

Output: [[ 44221  57767  88554   5834  88644  59688  19903  84322  62305  12436]
 [100042  98829 104836  99987  99886  62949 108600 100099  18560 106953]
 [101886 105376  49793 107930  82450 112886   7004 100576   7436 107382]
 [ 79451  79217   1333  12039 110313 102638  26021  93206 102089  76791]
 [114953   8051  89527  99006 113363 115288 113261 114857  14992  72737]
 [ 39473  45039  30620  19800  25686  83876  27675  58157  84783  81332]
 [ 71947  50184  76664  74494  52280  59157 101388  48151  14141  90237]
 [ 91333  88122  14821  98196  84565   7657  15084  10064  17114  33594]
 [104387  91671  10769  60213  63714  44392  37657  60726  35674 100352]
 [ 71010  71372  30688  62330  64956  17756  71105  29653  47349  46227]]


In [ ]:
# save the model to disk
filename = '/content/drive/MyDrive/Colab Notebooks/CE/models/near-neighbor/hep_th/tfidf.pickle'
pickle.dump(nearNeighbor, open(filename, 'wb'))

In [ ]:
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
_, result = loaded_model.kneighbors(X=sample_embeddings, n_neighbors=n_neighbor, return_distance=True)
if printOutput:
  print("\n======================== Nearest Neighbor ========================")
  print("\nInput shape: " + str(embeddings.shape))
  print("\nOutput shape: " + str(near_idx.shape))
  print("\nOutput type: " + str(type(near_idx)))
  print("\nOutput: " + str(result))


======================== Nearest Neighbor ========================

Input shape: (115458, 512)

Output shape: (10, 10)

Output type: <class 'numpy.ndarray'>

Output: [[ 44221  57767  88554   5834  88644  59688  19903  84322  62305  12436]
 [100042  98829 104836  99987  99886  62949 108600 100099  18560 106953]
 [101886 105376  49793 107930  82450 112886   7004 100576   7436 107382]
 [ 79451  79217   1333  12039 110313 102638  26021  93206 102089  76791]
 [114953   8051  89527  99006 113363 115288 113261 114857  14992  72737]
 [ 39473  45039  30620  19800  25686  83876  27675  58157  84783  81332]
 [ 71947  50184  76664  74494  52280  59157 101388  48151  14141  90237]
 [ 91333  88122  14821  98196  84565   7657  15084  10064  17114  33594]
 [104387  91671  10769  60213  63714  44392  37657  60726  35674 100352]
 [ 71010  71372  30688  62330  64956  17756  71105  29653  47349  46227]]
